repos:
- repo: https://github.com/psf/black
  rev: 23.9.1
  hooks:
    - id: black
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.306
  hooks:
    - id: ruff
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.12.0
  hooks:
    - id: isort
- repo: https://github.com/conventional-changelog/commitlint
  rev: v16.0.0
  hooks:
    - id: commitlint
      args: ['--config', '.commitlintrc.yml']
